apiVersion: v1
kind: Pod
metadata:
  name: root-user-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 0
        runAsNonRoot: false